export const explicitContent: string[] = [
    "Erotic",
    "Romance",
    "Erotica",
    "M M Romance",
    "BDSM",
    "Erotic Romance",
    "Shapeshifters",
    "M F Romance",
    "Menage",
    "Reverse Harem",
    "Polyamory",
    "Gay",
    "M M Contemporary",
    "Gay For You",
    "Bisexual",
    "M M M",
    "Queer",
    "NSFW",
    "Lesbian",
    "Erotic Horror",
    "Polyamorous",
    "Harem",
    "Shojo",
    "Yuri",
    "M M Fantasy",
    "M M Paranormal",
    "Gay Erotica",
    "M M Young Adult",
    "Shounen Ai",
    "漫画",
    "Harlequin Nocturne",
    "Erotic Paranormal Romance",
    "Omegaverse",
    "Silhouette",
    "Loveswept",
    "Mira",
    "Harlequin Blaze",
    "Mills and Boon",
    "Futuristic Romance",
    "Harlequin Teen",
    "Supernatural Romance",
    "adult",
    "LGBT",
    "Polygamy",
];