name: (DEV) Build and Deploy
on:
  push:
    branches:
    - dev
    
  pull_request:
    branches:
    - dev
jobs:
  test:
    timeout-minutes: 45
    runs-on: ubuntu-latest

    # sequence of tasks that will be executed as part of the job
    steps:

      #Check out to the develop branch
      - name: Checkout dev
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #Install node.js
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
        
      #Install yarn
      - name: Install yarn
        run: npm install yarn -g
        
      - name: Install packages
        run: yarn install

      #Run tests on the entire repository
      - name: Test
        working-directory: ./
        run: |
          yarn nx run-many --target=test --all --skip-nx-cache --parallel --coverage
          yarn nx run-many --target=lint --all --skip-nx-cache --parallel
          
      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          
# jobs:
#   dev_build:
#     name: Lint, Test & Build
#     environment: development
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout Repo
#       uses: actions/checkout@v3
      
#     - name: Install Dependencies
#       run: yarn install --frozen-lockfile
    
#     - name: Build Project
#       run: yarn build:app:dev && yarn build:api:dev

#     - name: Lint Project
#       run: yarn lint
      
#     - name: Test Project
#       run: yarn test
    
#     - name: SonarCloud Build and Analyze
#       uses: SonarSource/sonarcloud-github-action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
#     - name: Upload coverage reports to Codecov
#       uses: codecov/codecov-action@v3
#       env: 
#         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
        
#     - name: Archive Build Artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: dist-artifact
#         path: dist
#         retention-days: 1
