name: (DEV) Lint and Test
on:
  push:
    branches:
    - dev
    
  pull_request:
    branches:
    - dev
    
jobs:
  dev_build:
    name: Lint and Test
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Create .env file
      env:
        NX_MONGO_DB_URL: ${{ secrets.NX_MONGO_DB_URL }}
        NX_MONGO_DB_TEST: ${{ secrets.NX_MONGO_DB_TEST }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        
      run: |
          cat <<EOF > .env
          NX_ENVIRONMENT=development
          NX_MONGO_DB_URL="$NX_MONGO_DB_URL"
          NX_MONGO_DB_TEST="$NX_MONGO_DB_TEST"
          AWS_BUCKET_NAME="$AWS_BUCKET_NAME"
          AWS_BUCKET_REGION="$AWS_BUCKET_REGION"
          AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
          AWS_SECRET_KEY="$AWS_SECRET_KEY"
          EOF

          echo "cat .env"
          
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    
#     - name: Build Project
#       run: yarn build:app:dev && yarn build:api:dev

    - name: Lint Project
      run: yarn lint
      
    - name: Test Project
      working-directory: ./
      run: |
          yarn test
        # yarn nx run-many --target=lint --all --skip-nx-cache --parallel=6

    - name: E2E Tests
      working-directory: ./
      run: |
          yarn nx e2e encompass-e2e --coverage
          yarn nx e2e api-e2e --coverage
        # yarn nx run-many --target=lint --all --skip-nx-cache --parallel=6

    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
