name: (DEV) Build and Deploy
on:
  push:
    branches:
    - dev
    
  pull_request:
    branches:
    - dev
  
jobs:
  dev_build:
    name: Lint, Test & Build
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    
    - name: Build Project
      run: yarn build:app:dev && yarn build:api:dev

    - name: Lint Project
      run: yarn lint
      
    - name: Test Project
      run: yarn test --coverage
    
    - name: Codecov
      uses: codecov/codecov-action@v3
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        
    - name: Archive Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist-artifact
        path: dist
        retention-days: 1
