name: (MAIN) Lint And Test
on:
  push:
    branches:
    - main
    
jobs:
  prod_build:
    name: Lint and Test
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - name: Create .env.prod file
      env:
        NX_MONGO_DB_URL: ${{ secrets.NX_MONGO_DB_URL }}
        NX_MONGO_DB_TEST: ${{ secrets.NX_MONGO_DB_TEST }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_BUCKET_REGION: ${{ secrets.AWS_BUCKET_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        
      run: |
          cat <<EOF > .env
          NX_ENVIRONMENT=development
          NX_MONGO_DB_URL="$NX_MONGO_DB_URL"
          NX_MONGO_DB_TEST="$NX_MONGO_DB_TEST"
          AWS_BUCKET_NAME="$AWS_BUCKET_NAME"
          AWS_BUCKET_REGION="$AWS_BUCKET_REGION"
          AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
          AWS_SECRET_KEY="$AWS_SECRET_KEY"
          EOF

          echo "cat .env.prod"
          
    # #Install node.js
    # - name: Use Node.js 18
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '18'
        
      #Install yarn
    - name: Install yarn
      run: npm install yarn -g
        
    - name: Install packages
      run: yarn install
    
    # - name: Build Project
    #   run: yarn build:app:prod && yarn build:api:prod

    - name: Lint Project
      run: yarn lint
      
    - name: Test Project
      working-directory: ./
      run: |
          yarn test
      # yarn nx run-many --target=lint --all --skip-nx-cache --parallel=6
    
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage